
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 07 18:00:26 CEST 2017
//----------------------------------------------------

package esercizio5;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PROCEDURE = 10;
  public static final int INTEGER_CONSTANT = 30;
  public static final int READ = 15;
  public static final int ELSE = 29;
  public static final int ADDING_OPERATOR = 23;
  public static final int THEN = 17;
  public static final int WHILE = 18;
  public static final int NOT = 25;
  public static final int END = 20;
  public static final int IDENTIFIER = 6;
  public static final int TRUE = 26;
  public static final int SEPARATOR = 28;
  public static final int IF = 16;
  public static final int WRITE = 14;
  public static final int PROGRAM = 5;
  public static final int MULTIPLYING_OPERATOR = 24;
  public static final int DO = 19;
  public static final int BEGIN = 13;
  public static final int BOOLEAN = 12;
  public static final int CHARACTER_CONSTANT = 32;
  public static final int EOF = 0;
  public static final int END_PROGRAM = 8;
  public static final int FALSE = 27;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int ASSIGN = 21;
  public static final int INTEGER = 11;
  public static final int RPAR = 3;
  public static final int RELATIONAL_OPERATOR = 22;
  public static final int STRING_CONSTANT = 31;
  public static final int INSTRUCTION_SEPARATOR = 7;
  public static final int VAR = 9;
  public static final int LPAR = 2;
}

