package circuit;

//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 27 16:04:38 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
	/* terminals */
	public static final int RESISTOR = 5;
	public static final int PAR = 3;
	public static final int error = 1;
	public static final int END = 4;
	public static final int EOF = 0;
	public static final int SEQ = 2;
}
